version: '2'

services:
  app:
    build: ./app
    # command: -datadir=node
    volumes:
      - ./app:/app
    command:
      -printtoconsole
      -testnet=1
      -rest
      -rpcallowip=0.0.0.0/0
      -rpcpassword=bar
      -rpcport=18333
      -rpcuser=foo
      -server
    ports:
      - 18333:18333
